name: example
description: Demonstrates how to use the logging_flutter plugin.
publish_to: "none"

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  logging_flutter:
    path: ../

  logging: "^1.1.0"

flutter:
  uses-material-design: true
